FROM ubuntu

ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && \
    apt-get install -y ftp \
    && apt-get install  -y python3 \
    && apt-get install iputils-ping -y \
    && apt-get install arp-scan -y \
    && apt-get install net-tools -y \
    && apt-get install tcpdump -y \
    && apt-get install python3-scapy -y \