FROM python:3.8-slim-buster

RUN pip install pipenv

ENV PROJECT_DIR /project/server

WORKDIR ${PROJECT_DIR}

COPY Pipfile Pipfile.lock ${PROJECT_DIR}/

RUN pipenv install --system --deploy

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0","--port=80"]
